In [1]:
import torch
import numpy as np

In [2]:
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 3*x**2 + 5*x + 1
y

tensor(31., grad_fn=<AddBackward0>)

In [3]:
y.backward() # dy/dx

In [4]:
x.grad

tensor(29.)

In [5]:
# 3x**2 + 6x + 5 when x=2 => 12+12+5=29 

### gradient multi step

In [6]:
x = torch.tensor([[1.,2,3],[3,2,1]], requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [7]:
y = 3*x + 2
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [8]:
z = 2*y**2
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [9]:
out = z.mean()
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [10]:
out.backward() # dout/dx when x
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])


### Turn off tracking

- .requires_grad_(True) (or False)
- with torch.no_grad():
- .detach()

In [12]:
x = torch.tensor(2.0, requires_grad=True)
y = x * x
u = y #.detach()
z = u * x # z = x**3

z.sum().backward() # 3x**2 -> 3*2**2=12
x.grad

tensor(12.)

In [3]:
x = torch.tensor(2.0, requires_grad=True)
y = x * x
u = y.detach()
z = u * x * x

z.backward() #  u * 2x = 4 * 2*2 = 16
x.grad

tensor(16.)