In [1]:
import torch
import numpy as np

### Indexing

In [2]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
x[:,1]

tensor([1, 3, 5])

In [4]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

### reshape and view

In [6]:
x = torch.arange(10)

In [7]:
x.reshape(2,5), x.view(2,5)

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]))

### Tensor operations

In [9]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


In [10]:
torch.add(a, b)

tensor([5., 7., 9.])

In [11]:
a.add_(b)  # a += b
a

tensor([5., 7., 9.])

In [12]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(torch.add(a,b).sum())

tensor(21.)


### Dot products

In [13]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b)) # for reference
print()
print(a.dot(b))

tensor([ 4., 10., 18.])

tensor(32.)


### Matrix multiplication

In [14]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [15]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [16]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [17]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


### Matrix multiplication with broadcasting

In [21]:
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


In [23]:
print(torch.mm(t1, t2).size())

RuntimeError: self must be a matrix

In [26]:
(t1@t2).size()

torch.Size([2, 3, 5])

### Saving Memory