In [1]:
import torch
import numpy as np

### Create tensor

In [2]:
x = torch.zeros(4, 3, dtype=torch.int64)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [3]:
x = torch.arange(0,18,2).reshape(3,3)
x

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [4]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


In [6]:
print('Old:', x.type())

x = x.type(torch.int)

print('New:', x.type())

Old: torch.LongTensor
New: torch.IntTensor


### create from numpy

In [8]:
arr = np.array([1,2,3,4,5])
x = torch.from_numpy(arr)
x

tensor([1, 2, 3, 4, 5])

In [10]:
arr2 = np.arange(0.,12.).reshape(4,3)
x2 = torch.from_numpy(arr2)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

### Random Number

In [11]:
x = torch.rand(4, 3)
x

tensor([[0.7005, 0.0575, 0.8775],
        [0.9391, 0.2156, 0.5309],
        [0.6435, 0.0107, 0.4198],
        [0.4182, 0.1608, 0.7109]])

In [12]:
x = torch.randint(0, 5, (4, 3))
x

tensor([[0, 4, 2],
        [0, 3, 1],
        [0, 3, 3],
        [4, 4, 1]])

In [13]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


### Tensor attributes

In [16]:
x.shape, x.size()

(torch.Size([2, 3]), torch.Size([2, 3]))

In [18]:
x.device

device(type='cpu')